# This workflow uses actions that are not certified by GitHub.
name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Change directory
      run: cd viikko2/gradle-test/
    - name: Print working directory
      run: pwd
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: viikko2/gradle-test/gradlew test
    - name: Code coverage rapost
      run: viikko2/gradle-test/gradlew jacocoTestReport
    - name: checkstyle
      run: viikko2/gradle-test/gradle checkstyleMain
    - name: Data to codecov
      run: bash <(curl -s https://codecov.io/bash)
