# This workflow uses actions that are not certified by GitHub.
name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      working-directory: ./viikko2/gradle-test
      run: chmod +x gradlew
    - name: Test with Gradle
      working-directory: ./viikko2/gradle-test
      run: gradlew test
    - name: Code coverage rapost
      working-directory: ./viikko2/gradle-test
      run: gradlew jacocoTestReport
    - name: checkstyle
      working-directory: ./viikko2/gradle-test
      run: gradle checkstyleMain
    - name: Data to codecov
      run: bash <(curl -s https://codecov.io/bash)
